### ISSUE TITLE
deprecated section for rels

### ISSUE THREAD

**Issue by pfefferle** [webfinger/webfinger.net#18]
Should we add a "deprecated" section on the rel page, to list for example:

* http://webfinger.net/rel/acct-desc
* http://webfinger.net/rel/service

**Comment by willnorris** [comment]
does anyone actually use those?  Have you seen them in the wild?

**Comment by pfefferle** [comment]
Only in some legacy code https://github.com/search?q=http%3A%2F%2Fwebfinger.net%2Frel%2Facct-desc&type=Code

**Comment by willnorris** [comment]
probably not worth bothering with then.

**Comment by pfefferle** [comment]
OK, but what about a descriptive 404 page: https://help.github.com/articles/custom-404-pages/

**Comment by willnorris** [comment]
sure, go for it
