### ISSUE TITLE
Stop using CloudFlare

### ISSUE THREAD

**Issue by myfreeweb** [webfinger/webfinger.net#21]
Currently, webfinger.net is "protected" with CloudFlare, which results in a CAPTCHA when visited through Tor.

Please stop using CloudFlare. Or, at least, whitelist Tor: https://support.cloudflare.com/hc/en-us/articles/203306930

But seriously, stop using CloudFlare. We don't need the whole internet to be connected through one company.

**Comment by willnorris** [comment]
Tor traffic has been whitelisted.

**Comment by myfreeweb** [comment]
Thanks!
