### ISSUE TITLE
Project dead?

### ISSUE THREAD

**Issue by odinho** [webfinger/webfinger.net#25]
Having a look at this since Blockstack (https://blockstack.org/) needs some way to "prove you own the email address" for your ID (i.e. my ID is odinho.id - https://core.blockstack.org/v1/users/odinho.id). E.g. here's a verification for my GitHub user: https://gist.github.com/odinho/cf5d6bcd550835597c85e2331c69a679

I was going to make the team take a look at WebFinger again if they haven't, but not sure I can send them that way since there seems to be little-to-no action since 2013? webfist.org does not load. Also seems to have very little traction sadly.

What is current status? Maybe that could be listed on the website if it's not fully dead, but just limping along. Or did something else come along taking over?

**Comment by pfefferle** [comment]
The project is not dead, but at a final state: https://webfinger.net/spec/

It is widely adopted by the OpenID Connect Community and the Fediverse Community (OStatus and Mastodon).

But it seems to be a good idea to remove Webfist from the lookup /cc @willnorris

**Comment by odinho** [comment]
Cool!

But there is no fallback then? No way of what webfist was doing? So it'll work for people that control their domains, but not for e.g. Gmail?

**Comment by willnorris** [comment]
webfist has been disabled on client.webfinger.net.

**Comment by willnorris** [comment]
Closing this issues as long-stale.  I will note however for anyone that find this in the future that webfinger is not a good mechanism to verify ownership of an email address.  acct URIs look similar to email addresses, but they are not email addresses.  There is no guarantee that a given service provider maps them to each other.  If your goal is to verify ownership of an email address, the best option is to actually send them an email with a code or magic link.
