### ISSUE TITLE
Is webfinger able to distinguish between 2 services on the same URI?

### ISSUE THREAD

**Issue by r3pek** [webfinger/webfinger.net#26]
I really don't know if I'm asking in the right place, but I need to understand this better.
I'm trying to understand why all this new federated social sites (mastodon, diaspora*, friendica, etc), are using webfinger to find the other server, but yet, it looks like all are requiring an unique ID to each other. If didn't make myself clear, it's impossible at the moment to use the same ID (say acc@example.com) on all this networks, because the namespace would collide (well, there can only be one .well-known/webfinger endpoint in one domain) and all of them provide their own implementation of webfinger for the federation part.

Now, I don't know if this is "by-design", but it really seams weird that something that is federated and "advertised" as being able to be self-hosted, we should assume that one user can have several of this networks parked on his own domain, and that breaks the "single-id-to-rule-them-all", since it doesn't make much sense to exist an acc@mastodon.example.com, acc@diaspora.example.com, acc@firendica.example.com, since they're all the same person.

Now, i stumbled across [this](https://github.com/webfinger/archive/blob/master/wiki/DnsLookup.wiki) old wiki page, talking about SRV records, but still not making any assurance to use them. Since that is old, I'd like to ask what have you guys decided (and the why possibly?) in this matter, since the usage of SRV records could solve the "single-id-to-rule-them-all" issue. One other question is if this should be done on a webfinger level of application level, say, if a possible SRV lookup should be core to the webfinger spec, or if it could be delegated to the application using it.

I know that there are at least 2 bugs that I know of about SRV records on this networks, one for mastodon and one for diaspora, but one of them is really old and points the wiki page mentioned earlier, and the other basically says that it "would defeat the purpose of webfinger", but somehow I'm failing to understand how webfinger can solve this issue... (or maybe this isn't even an issue :(  )

Sorry for the long post.

**Comment by pfefferle** [comment]
Short answer: one `acct` URI can be used for all plattforms that you mentioned. I am working on several WordPress plugins, to make WordPress compatible to mastodon, gnu.social, diaspora and friendica. Most services support one protocol, so it doesn't matter at all and if they don't, the can extend the WebFinger JRD/XRD file with their specific endpoints. It only breaks if two services use the same `rel` for different functionalities.

**Comment by pfefferle** [comment]
Here is my JRD file: https://client.webfinger.net/lookup?resource=pfefferle%40notiz.blog

**Comment by r3pek** [comment]
was that "hand written" or you use the provided webfinger servers for those services? Yesterday I actually tried to build a "Webfinger Aggregator" to merge several responses together, but stopped working on it because mastodon and diaspora have "rel"s in common (OStatus for example). Since I'm not sure which one is needed, I decided to stop coding ;)

Is an "aggregator" a solution to a server that you have to configure yourself?

**Comment by pfefferle** [comment]
Oh, I see. This is a generated WebFinger file, but I implemented the functionality of all the mentioned services by myself... I do not use the diaspora, mastodon, ... service, but my WordPress is compatible. If you want to install all of these services and use one identifier for all of them, this is indeed a problem, because you have several similar `rel`s that are pointing to different API endpoints.

**Comment by pfefferle** [comment]
WebFinger is a unique identifier for only one domain. So if you want to have one global identifier, you have to install a service that supports all federated plattforms.

As far as I know, Friendica speaks all mentioned protocols.

**Comment by r3pek** [comment]
Exactly. Problem is I don't see documentation on how to build one and what rels are needed for what services, so, we're kinda with our hands tight on this :P

**Comment by pfefferle** [comment]
Here are some docs:

* https://diaspora.github.io/diaspora_federation/ (Diaspora, Friendica)
* https://github.com/OStatus/spec (gnu.social, Mastodon, Friendica)
* https://www.w3.org/TR/activitypub/ (Mastodon)

**Comment by willnorris** [comment]
If diaspora and mastadon are using the same rel values in their webfinger documents, then *in theory* they should be implementing the same protocol.  And if so, then you shouldn't actually need to install both.  That's the whole promise of the distributed web/fediverse/indie web/pick your buzzword.  Standardize on the protocols themselves, and you can run whichever implementation you want to (for example, @pfefferle built his own on top of WordPress).  Now of course, in practice we're still some ways off from having a diaspora instance talk to mastadon.

**Comment by willnorris** [comment]
Closing this since there doesn't seem to be anything more to do.  However, with the current surge of interest in Mastodon, Fediverse, and ActivityPub, the discussion is still most certainly still relevant. Two servers which advertise support of the same protocol (typically through rel value and/or content-type) *should* interoperate.
