### ISSUE TITLE
Add support for email style local account

### ISSUE THREAD

**Issue by mediaformat** [webfinger/webfinger.net#28]
My understanding of the [spec](https://datatracker.ietf.org/doc/html/rfc7565#section-4) is that it is meant to support an email address as a local identifier: 

> A common scenario is for a user to register with a service provider
   using an identifier (such as an email address) that is associated
   with some other service provider.  For example, a user with the email
   address "juliet@capulet.example" might register with a commerce
   website whose domain name is "shoppingsite.example".  In order to use
   her email address as the localpart of the 'acct' URI, the at-sign
   character (U+0040) needs to be percent-encoded as described in
   [[RFC3986](https://datatracker.ietf.org/doc/html/rfc3986)].  Thus, the resulting 'acct' URI would be
   "acct:juliet%40capulet.example@shoppingsite.example".

The webfinger.net site doesn't currently support this:

> 16:05:14 Looking up WebFinger data for acct:bob@alice.com@example.social
16:05:14 GET https://alice.com%40example.social/.well-known/webfinger?resource=acct%3Abob%40alice.com%40example.social
16:05:14 Error getting JRD: parse https://alice.com%40example.social/.well-known/webfinger?resource=acct%3Abob%40alice.com%40example.social: invalid URL escape "%40"

Should I open a PR for this?

**Comment by willnorris** [comment]
yeah, feel free to open a PR, I suspect it will probably be in https://github.com/webfinger/go-webfinger unless we're messing up the encoding/decoding inside of https://github.com/webfinger/client.webfinger.net ?

**Comment by willnorris** [comment]
I'm curious, are there any systems that are using email addresses for the local part like this in practice?  Would be good to have a concrete test case

**Comment by pfefferle** [comment]
WordPress! We had an issue for the AP Plugin: https://github.com/pfefferle/wordpress-activitypub/issues/152

**Comment by willnorris** [comment]
This should now be fixed on webfinger.net
