### ISSUE TITLE
The `rel` URLs seem broken

### ISSUE THREAD

**Issue by pfefferle** [webfinger/webfinger.net#29]
See:

* https://webfinger.net/rel/avatar
* https://webfinger.net/rel/profile-page

**Comment by willnorris** [comment]
oops... got a little to eager with the switch to hugo.  Thanks, I'll work on that and clean up some other layout issues.

**Comment by willnorris** [comment]
okay, immediate problem fixed (rel pages now work).  Still more layout cleanup to do, but that'll be separate.
