### ISSUE TITLE
Error: 09:50:53 Error getting JRD: invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by richardazia** [webfinger/webfinger.net#34]
I installed Webfinger, and tested to see whether it was working on the wordpress blog but I came across the error message above.
Webfinger is looking here: 
09:50:53 GET https://www.main-vision.com/.well-known/webfinger?resource=acct%3Aadmin%40www.main-vision.com when I would like it to look here: 
https://www.main-vision.com/richard/blog/.well-known/webfinger?resource=acct%3Aadmin%40www.main-vision.com

I ran a quick test to verify that my impression was correct. 

The question is: Do I move the json file into the route, or is there a way to tell webfinger to look elsewhere?

**Comment by pfefferle** [comment]
Maybe this helps https://github.com/Automattic/wordpress-activitypub#what-if-you-are-running-your-blog-in-a-subdirectory

**Comment by richardazia** [comment]
I'll try it.

**Comment by richardazia** [comment]
The solution that worked for me was to create the .well-known folder in my web root directory. I then created a webfinger.json file and added the right json data to it. Since then, it works seamlessly. It is working on Mastodon and Calckey.
